from flask import Flask, render_template, jsonify, request
import os
import joblib
import pandas as pd
import numpy as np
import datetime
from dateutil.relativedelta import relativedelta
import json

app = Flask(__name__)

# --- Inisialisasi Model dan Data ---
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
MODEL_DIR = os.path.join(BASE_DIR, 'model')
DATA_PATH = os.path.join(BASE_DIR, '..', 'dataset', 'komoditas_beras_2022_2026.csv')
ADDITIONAL_DATA_PATH = os.path.join(BASE_DIR, '..', 'dataset', 'komoditas_beras_tambahan.csv')

# Global Variables
model = None
scaler_X = None
scaler_y = None
ts = None
monthly_actual = None
HISTORIS_DATA = []
actual_js = []
forecast_js = []
months_id = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Ags", "Sep", "Okt", "Nov", "Des"]

def load_model_and_data():
    global model, scaler_X, scaler_y, ts, monthly_actual, HISTORIS_DATA, actual_js, forecast_js
    
    # Load Model
    model = joblib.load(os.path.join(MODEL_DIR, 'bayesian_ridge_model.pkl'))
    scaler_X = joblib.load(os.path.join(MODEL_DIR, 'scaler_X.pkl'))
    scaler_y = joblib.load(os.path.join(MODEL_DIR, 'scaler_y.pkl'))

    # Load Data Historis
    df = pd.read_csv(DATA_PATH)
    
    # Check if there is injected/additional data
    if os.path.exists(ADDITIONAL_DATA_PATH):
        df_add = pd.read_csv(ADDITIONAL_DATA_PATH)
        df_add = df_add.drop_duplicates(subset=['Date_Param'], keep='last')
        df = pd.concat([df, df_add], ignore_index=True)
        
    df['Date_Param'] = pd.to_datetime(df['Date_Param'])
    ts_temp = df.groupby('Date_Param')['Price'].mean().reset_index()
    ts_temp = ts_temp.rename(columns={'Date_Param': 'Date', 'Price': 'Price'})
    ts_temp = ts_temp.sort_values('Date').set_index('Date')
    ts = ts_temp.resample('D').mean().ffill()

    # Generate fitur lag 1 sampai 7
    df_feat = ts[['Price']].copy()
    for i in range(1, 8):
        df_feat[f'lag_{i}'] = df_feat['Price'].shift(i)
    df_feat = df_feat.dropna()

    # Generate fitted values for historical
    X_hist = df_feat[['lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_5', 'lag_6', 'lag_7']]
    X_hist_sc = scaler_X.transform(X_hist)
    y_pred_sc = model.predict(X_hist_sc)
    y_pred = scaler_y.inverse_transform(y_pred_sc.reshape(-1, 1)).ravel()

    df_feat['Predicted'] = y_pred

    # Resample to monthly for dashboard
    monthly_actual = ts['Price'].resample('ME').mean()
    monthly_pred = df_feat['Predicted'].resample('ME').mean()

    # Calculate dynamic HISTORIS_DATA for Jinja
    HISTORIS_DATA.clear()
    for dt in monthly_actual.index:
        actual_val = monthly_actual[dt]
        pred_val = monthly_pred.get(dt, np.nan)
        if pd.isna(pred_val):
            continue
        selisih = actual_val - pred_val
        error_pct = abs(selisih / actual_val) * 100
        month_name = f"{months_id[dt.month-1]} {dt.year}"
        HISTORIS_DATA.append({
            "bulan_raw": dt.strftime("%Y-%m"),
            "bulan": month_name,
            "aktual": round(actual_val),
            "prediksi": round(pred_val),
            "selisih": round(selisih),
            "error_pct": round(error_pct, 2)
        })
    HISTORIS_DATA.reverse()

    # Generate next 4 months for FORECAST_DATA
    target_forecast_date = ts.index[-1] + relativedelta(months=4)
    target_forecast_date = target_forecast_date.replace(day=28) # safe day
    next_4_months = forecast_future_internal(target_forecast_date)
    monthly_forecast = next_4_months['Price'].resample('ME').mean()

    # Overwrite mock_data.js with real data!
    actual_js.clear()
    for dt in monthly_actual.index:
        actual_js.append({
            "month": f"{months_id[dt.month-1]} {dt.year}",
            "price": round(monthly_actual[dt])
        })

    forecast_js.clear()
    last_price = actual_js[-1]['price']
    for dt in monthly_forecast.index:
        if dt <= monthly_actual.index[-1]:
            continue
        price = round(monthly_forecast[dt])
        change = round(((price - last_price) / last_price) * 100, 2)
        forecast_js.append({
            "month": f"{months_id[dt.month-1]} {dt.year}",
            "price": price,
            "change": change
        })
        last_price = price
        if len(forecast_js) == 4:
            break

    js_content = f"""// AUTO-GENERATED BY app.py from REAL BAYESIAN RIDGE MODEL
const ACTUAL_DATA = {json.dumps(actual_js)};
const FORECAST_DATA = {json.dumps(forecast_js)};
const MODEL_METRICS = {{ mape: 0.0502, r2: 0.9961, mae: 7.89, rmse: 12.01 }};
"""
    with open(os.path.join(BASE_DIR, 'static', 'js', 'mock_data.js'), 'w') as f:
        f.write(js_content)

def forecast_future_internal(target_date):
    """Forecast future daily values up to target_date using Auto-regression"""
    last_date = ts.index[-1]
    last_prices = ts['Price'].iloc[-7:].tolist()
    last_prices.reverse() # [lag_1, lag_2, ..., lag_7]
    
    current_date = last_date
    future_preds = []
    future_dates = []
    
    while current_date <= target_date:
        current_date += datetime.timedelta(days=1)
        X_new = pd.DataFrame([last_prices[:7]], columns=['lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_5', 'lag_6', 'lag_7'])
        X_new_sc = scaler_X.transform(X_new)
        pred_sc, std_sc = model.predict(X_new_sc, return_std=True)
        pred = scaler_y.inverse_transform(pred_sc.reshape(-1, 1)).ravel()[0]
        std = std_sc[0] * scaler_y.scale_[0] 
        
        future_preds.append((pred, std))
        future_dates.append(current_date)
        
        last_prices.insert(0, pred)
        last_prices.pop()
        
    forecast_df = pd.DataFrame(future_preds, columns=['Price', 'Std'], index=future_dates)
    return forecast_df

# Call once on startup
load_model_and_data()

@app.route('/')
def dashboard():
    return render_template('dashboard.html', 
                          aktual=actual_js[-1]['price'], 
                          aktual_month=actual_js[-1]['month'],
                          pred=forecast_js[0]['price'],
                          pred_month=forecast_js[0]['month'],
                          pred_change=forecast_js[0]['change'])

@app.route('/historis')
def historis():
    return render_template('historis.html', data_historis=HISTORIS_DATA)

@app.route('/prediksi')
def prediksi():
    return render_template('prediksi.html')

@app.route('/model')
def model_info():
    return render_template('model_info.html')

@app.route('/api/predict')
def api_predict():
    month_val = request.args.get('month', '')
    if not month_val:
        return jsonify({"error": "Bulan tidak valid"}), 400
    
    try:
        dt = datetime.datetime.strptime(month_val, "%Y-%m")
        # Target is the end of the requested month
        target_date = dt + relativedelta(months=1) - relativedelta(days=1)
        month_name = months_id[dt.month-1]
        formatted_month = f"{month_name} {dt.year}"
    except ValueError:
        return jsonify({"error": "Format bulan salah"}), 400

    if target_date <= ts.index[-1]:
        return jsonify({
            "month": formatted_month,
            "predicted": round(monthly_actual.iloc[-1]),
            "lower": round(monthly_actual.iloc[-1]) - 50,
            "upper": round(monthly_actual.iloc[-1]) + 50
        })

    forecast_df = forecast_future_internal(target_date)
    mask = (forecast_df.index.year == dt.year) & (forecast_df.index.month == dt.month)
    month_data = forecast_df[mask]
    
    if len(month_data) == 0:
         return jsonify({"error": "Gagal menghitung rentang"}), 400
         
    pred_mean = month_data['Price'].mean()
    std_mean = month_data['Std'].mean()
    
    margin = 1.96 * std_mean
    
    return jsonify({
        "month": formatted_month,
        "predicted": round(pred_mean),
        "lower": round(pred_mean - margin),
        "upper": round(pred_mean + margin)
    })

@app.route('/api/add_actual', methods=['POST'])
def add_actual():
    data = request.json
    month_val = data.get('month')
    price = data.get('price')
    
    if not month_val or not price:
        return jsonify({"error": "Data tidak lengkap"}), 400
        
    try:
        dt = datetime.datetime.strptime(month_val, "%Y-%m")
        # Inject data point on the 1st of the month so that forward-fill populates the whole month with this price.
        # This guarantees the monthly average calculation aligns with the injected price.
        inject_date = dt.replace(day=1).strftime("%Y-%m-%d")
        price = float(price)
    except Exception as e:
        return jsonify({"error": str(e)}), 400

    new_data = pd.DataFrame([{"Date_Param": inject_date, "Price": price}])
    new_data.to_csv(ADDITIONAL_DATA_PATH, mode='a', header=not os.path.exists(ADDITIONAL_DATA_PATH), index=False)
    
    # Reload model
    try:
        load_model_and_data()
    except Exception as e:
        return jsonify({"error": "Gagal memuat ulang data"}), 500
        
    return jsonify({"message": "Berhasil menyuntikkan data aktual baru. Model telah diperbarui!"})

if __name__ == '__main__':
    app.run(debug=True, port=5000)
